### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by vkazheng** [sapirnoam/WarrantyTrack#8]
first of all great solution! is there a way that we can allow each user to only be able to generate and see their own case, categorise this as another level of user role?

**Comment by DevNoam** [comment]
Hey I'm glad you found my project helpful :)

That's a great idea, I'm currently investigating implementing this feature.

**Comment by DevNoam** [comment]
Hi again.
I've added your requested feature.
You can search even further using the search bar.
For example, searching "Admin" will take you to all the cases with the keyword Admin, resulting in similar behavior to the new added feature.
![image_2022-09-16_213842748](https://user-images.githubusercontent.com/42315483/190708769-0f8bdfab-f0ca-4e23-a295-07331a9f6490.png)

**Comment by vkazheng** [comment]
Hi Noam, will try it out! thanks.
